# Generated by Django 3.2.7 on 2022-12-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='specification',
            field=models.ImageField(blank=True, null=True, upload_to='static/product'),
        ),
    ]
